project_id = "yzuvyvtspdjmewuakpkn"

[functions.analyze-workforce]
verify_jwt = false

[functions.import-questions]
verify_jwt = true

[functions.extract-questions]
verify_jwt = true

[functions.import-csv-questions]
verify_jwt = false

[functions.seed-questions]
verify_jwt = false
